### ISSUE TITLE
Разнесение поступлений денежных средств по 1С

### ISSUE THREAD

**Issue by zimov** [4orever/ppc-main#3]
При загрузке данных из файлика - ЕРП корректно определяет контрагентов. Даже если не всегда корректно определяет, то можно поставить правильно вручную ( это актуально по приходам от физ лиц). Однако при следующей операции, когда мы подвязываем поступивший платеж и заказ покупателя, возникает необходимость сначала указать плательщика ( а что бы его найти - нужно зайти в таблицу "заказы покупателей"), что не очень удобно. 
Задача - сделать так, что бы к поступившему платежу автоматический подвязывался к/а , а пользователю было необходимо только выбрать номер заказа покупателя.

**Comment by 4orever** [comment]
ppc-main не имеет никакого отношения к 1С
